services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: two_tier_db
    volumes:
      - ./mysql_data:/var/lib/mysql
  

    networks:
      - twotier
    ports:
      - "3303:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","uroot","-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  flaskapp:
    build:
      context: /home/ubuntu/github_repos/two-tier-flask-app
    container_name: flaskapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DB: two_tier_db
    networks:
      - twotier
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      
volumes:
  mysql_data:

networks:
  twotier:
